name 'disable_smb1server'
issues_url 'https://github.com/yvovandoorn/disable_smb1server/issues'
source_url 'https://github.com/yvovandoorn/disable_smb1server'
maintainer 'Yvo van Doorn'
maintainer_email 'yvo.vandoorn@gmail.com'
license 'apachev2'
description 'Installs/Configures disable_smb1server'
long_description 'Installs/Configures disable_smb1server'
version '0.1.0'
